# Generated by Django 5.2 on 2025-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
